---
- name: "[system_configuration]"
  hosts: localhost
  become: yes
  gather_facts: false
  tasks:
    - name: Set hostname -> {{ my_hostname }}
      hostname:
        name: "{{ my_hostname }}"


    - name: Set timezone -> {{ my_timezone }}
      timezone:
        name: "{{ my_timezone }}"


    - name: Set localisation files -> '{{ my_locale }}'
      locale_gen:
        name: "{{ my_locale }}"
        state: present


    - name: Generate SSH keys if none is present
      openssh_keypair:
        path: ~pi/.ssh/id_rsa
        size: 4096
        force: no
        type: rsa


    - name: Tweak /boot/config.txt
      ini_file:
        path: /boot/config.txt
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        backup: yes
        no_extra_spaces: yes
      loop:
        - { section: '', option: 'dtparam=i2c_arm', value: 'off' }
        - { section: '', option: 'dtparam=spi', value: 'off' }
        - { section: '', option: 'dtparam=audio', value: 'on' }
        - { section: 'all', option: 'start_x', value: 0 }
        - { section: 'all', option: 'enable_uart', value: 0 }
        - { section: 'all', option: 'gpu_mem', value: 16 }

    - name: Copy /etc/hosts
      template:
        src: system_configuration/hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0664'
      ignore_errors: true

    - name: Copy /etc/dhcpcd.conf
      template:
        src: system_configuration/dhcpcd.conf
        dest: /etc/dhcpcd.conf
        owner: root
        group: netdev
        mode: '0664'
      notify: restart network


    - name: Enable sshd service
      service:
        name: sshd
        state: started
        enabled: yes


    - name: Install missing packages
      apt:
        name: "{{ item }}"
      loop:
        - ca-certificates
        - curl
        - net-tools
      loop_control:
        label: "{{ item }}"


    - name: Create a crontab job to update Raspbian
      cron:
        name: "OS auto updates"
        special_time: weekly
        job: "apt-get -y upgrade"

  handlers:
    - name: restart network
      service:
        name:
          - dhcpcd
          - networking
        state: restarted
