---
- name: "[system_configuration]"
  hosts: localhost
  become: yes
  gather_facts: false
  tasks:
    - name: Set hostname -> {{ my_hostname }}
      hostname:
        name: "{{ my_hostname }}"


    - name: Set timezone -> {{ my_timezone }}
      timezone:
        name: "{{ my_timezone }}"


    - name: Set localisation files -> '{{ my_locale }}'
      locale_gen:
        name: "{{ my_locale }}"
        state: present


    - name: Copy /etc/hosts
      template:
        src: system_configuration/hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0664'


    - name: Change /etc/dhcpcd.conf
      blockinfile:
        path: /etc/dhcpcd.conf
        block: |
          interface eth0
          static ip_address={{ my_ip_address }}/24
          static routers={{ box_ip_address }}
          static domain_name_servers={{ dns1 }} {{ dns2 }}
      notify: restart network


    - name: Enable sshd service
      service:
        name: sshd
        state: started
        enabled: yes


    - name: Install missing packages
      apt:
        name: "{{ item }}"
      loop:
        - ca-certificates
        - curl
        - net-tools
      loop_control:
        label: "{{ item }}"


    - name: Create a crontab job to update Raspbian
      cron:
        name: "OS auto updates"
        special_time: weekly
        job: "apt-get -y upgrade"

  handlers:
    - name: restart network
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - dhcpcd
        - networking
