---
- name: "[docker]"
  hosts: localhost
  become: yes
  gather_facts: false
  tasks:

    # Install Docker
    # https://docs.docker.com/install/linux/docker-ce/debian/
    # Docker by apt-get is not compatible with Raspbian

    - name: Install python docker module
      pip:
        name: docker-py


    - name: Download Docker install script
      get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
      register: downloaded


    - name: Install Docker # noqa 503
      command: sh /tmp/get-docker.sh
      when: downloaded.changed


    - name: Add the user 'pi' to docker group
      user:
        name: pi
        groups: docker
        append: yes
      notify: restart Docker


    - meta: flush_handlers

  handlers:
    - name: restart Docker
      service:
        name: docker
        state: restarted
