---

- name: "[pihole]"
  hosts: localhost
  become: yes
  gather_facts: false
  tasks:

    - name: Create a pihole container on port 80
      docker_container:
        name: pihole
        image: pihole/pihole:latest
        state: started
        env:
          TZ: "{{ my_timezone }}"
          DNS1: "{{ dns1 }}"
          DNS2: "{{ dns2 }}"
          ServerIP: "{{ my_ip_address }}"
        ports:
          - "53:53/tcp"
          - "53:53/udp"
          - "67:67/udp"
          - "80:80/tcp"
          - "443:443/tcp"
        volumes:
          - "/etc/pihole/:/etc/pihole/"
          - "/etc/dnsmasq.d/:/etc/dnsmasq.d/"
        dns_servers:
          - 127.0.0.1
          - "{{ dns1 }}"
        capabilities:
          - NET_ADMIN
        network_mode: host
        restart_policy: 'unless-stopped'


    - name: Change pihole settings
      ini_file:
        path: "{{ item.file }}"
        section: null
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        no_extra_spaces: true
        backup: yes
      loop:
        - { file: /etc/pihole/setupVars.conf, option: PIHOLE_DNS_1, value: "{{ dns1 }}" }
        - { file: /etc/pihole/setupVars.conf, option: PIHOLE_DNS_2, value: "{{ dns2 }}" }
        - { file: /etc/pihole/setupVars.conf, option: IPV4_ADDRESS, value: "{{ my_ip_address }}" }
        - { file: /etc/pihole/setupVars.conf, option: DHCP_ROUTER, value: "{{ box_ip_address }}" }
        - { file: /etc/pihole/setupVars.conf, option: PIHOLE_DOMAIN, value: "{{ my_network_name }}" }
        - { file: /etc/pihole/setupVars.conf, option: WEBPASSWORD, value: "" }
      register: pihole_conf


    - name: "[Pihole] Restart container" # noqa 503
      docker_container:
        name: pihole
        state: started
        restart: yes
      when: pihole_conf.changed

