---
- name: "[radicale]"
  hosts: localhost
  become: yes
  gather_facts: false
  tasks:
    - name: Add packages prerequisites
      apt:
        name:
          - apache2-utils
          - python3
          - python3-pip


    - name: Add OS user 'radicale'
      user:
        name: radicale
        password: $6$mysecretsalt$9nQl7uSP.U5lQhRu/ZcCf/abvxUnWvDZMrTrbXMpXmQoA5gDmd4DYkIs/4gu5imDCD.UkGQG84jaSLhVeU8/C0 # = radicale
        uid: 1001
        shell: /bin/bash


    - name: Install Radicale application
      pip:
        name:
          - radicale
          - radicale[bcrypt]
          - passlib[bcrypt]
        executable: pip3
        state: present
        extra_args: --user radicale


    - name: Copy systemd service file (port {{ radicale_port }})
      copy:
        src: radicale/radicale.service
        dest: /lib/systemd/system/radicale.service


    - name: Create directories
      file:
        path: "{{ item }}"
        owner: radicale
        group: radicale
        state: directory
      with_items:
        - /var/log/radicale/
        - /home/radicale/.config/radicale/
        - /home/radicale/.config/systemd/user/


    - name: Copy main configuration file
      template:
        src: radicale/config
        dest: ~radicale/.config/radicale/config
        owner: radicale
        group: radicale
        mode: 0600
      notify: restart Radicale


    - name: Add '{{ radicale_account_name }}' account on your Radicale server
      htpasswd:
        path: /home/radicale/.config/radicale/users
        name: "{{ radicale_account_name }}"
        create: yes
        password: "{{ radicale_account_password }}"
        owner: radicale
        group: radicale
        crypt_scheme: bcrypt
        mode: 0640
      notify: restart Radicale


  handlers:
    - name: restart Radicale
      service:
        name: radicale
        enabled: true
        state: restarted
