---

- name: "[duplicacy]"
  hosts: localhost
  become: yes
  gather_facts: false
  tasks:
    - name: Download Duplicacy Web Server
      get_url:
        url: "https://acrosync.com/duplicacy-web/duplicacy_web_{{ os_arch_web }}_{{ duplicacy_web_version }}"
        dest: /usr/local/bin/duplicacy-web
        mode: 0500
      vars:
        duplicacy_web_version: 1.4.1
        os_arch_web: linux_arm # linux_arm osx_x64 linux_x64  freebsd_x64


    - name: Copy configuration files
      template:
        src: duplicacy/settings.json
        dest: ~/.duplicacy-web/settings.json
        owner: root
        group: root
        mode: '0600'


    - name: Create Duplicacy service file (port {{ duplicacy_port }})
      copy:
        src: duplicacy/duplicacy.service
        dest: /etc/systemd/system/
        mode: 0644
      notify: restart Duplicacy Web Server


    - name: Download Duplicacy CLI
      get_url:
        url: "https://github.com/gilbertchen/duplicacy/releases/download/v{{ duplicacy_cli_version }}/duplicacy_{{ os_arch_cli }}_{{ duplicacy_cli_version }}"
        dest: /usr/local/bin/duplicacy
        mode: 0555
      vars:
        duplicacy_cli_version: 2.7.1
        os_arch_cli: linux_arm # linux_arm freebsd_x64 linux_arm64 linux_arm linux_i386 linux_x64 osx_x64

  handlers:
    - name: restart Duplicacy Web Server
      service:
        name: duplicacy
        enabled: true
        state: restarted
