---

- hosts: localhost
  become: true
  gather_facts: false
  tasks:
  
- import_playbook: 0.system_configuration.yml
  tags: [system_configuration]

- import_playbook: 1.docker.yml
  tags: [docker, pihole]

- import_playbook: 2.pihole.yml
  tags: [pihole]

- import_playbook: 3.radicale.yml
  tags: [radicale]

- import_playbook: 4.duplicacy.yml
  tags: [duplicacy]

...
